name: Generate library docs

on:
  push:
    branches: ["main", "docs-ci"]

env:
  NODE_VER: 16.x
  BASE_BRANCH: "dev"

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: "docs"

      - name: Config git
        run: |
          git config --global user.name "GitHub Actions (${{ github.workflow }})"
          git config --global user.email "65886108+KleinChiu@users.noreply.github.com"

      - name: Sync with base branch
        run: |
          git pull origin ${{ env.BASE_BRANCH }} --no-ff --autostash -X theirs --allow-unrelated-histories -s ort

      - name: Prepare Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"

      - name: Install dependencies
        run: "npm ci"

      - name: Generate docs
        run: "npm run docs"

      - name: Publish docs
        run: |
          git add docs
          git commit --amend -m "Generate docs from latest version"
          git push origin --force
        # uses: EndBug/add-and-commit@v9
        # with:
        #   add: "docs"
        #   default_author: github_actions
