name: Generate library docs

on:
  push:
    branches: ["dev"]

env:
  NODE_VER: 16.x

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: "docs"

      - name: Prepare Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"

      - name: Install dependencies
        run: "npm ci"

      - name: Generate docs
        run: "npm run docs"

      - name: Publish docs
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          default_author: github_actions
          pull: origin ${{ github.ref }} --no-ff --autostash -X theirs --allow-unrelated-histories
